spring:
  config:
    activate:
      on-profile: dev
  strategy: ant_path_matcher
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/DB
    username: root
    password: Rt566^77
    hikari:
      connection-timeout: 20000
      minimum-idle: 10
      maximum-pool-size: 10
      idle-timeout: 10000
      max-lifetime: 1000
      auto-commit: true
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQLDialect
      ddl-auto: update
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

# Application messages
application:
  message: dev activated
server:
  servlet:
    context-path: "/ota"
  port: 9080

api-key: c4884d13-6f95-44ab-b2b2-72b363fb6d3b